[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = {sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/NNJtHbr1qlYR1TmV1zNjd" , arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/NNJtHbr1qlYR1TmV1zNjd"}

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts", "@ccip/=lib/ccip/contracts/src/v0.8/", "@chainlink-local/=lib/chainlink-local/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
